// <auto-generated />
using System;
using Kariyer.Mail.Api.Common.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Kariyer.Mail.Api.Migrations
{
    [DbContext(typeof(MailDbContext))]
    [Migration("20260508200000_EnsureMissingColumns")]
    partial class EnsureMissingColumns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
